--ALTER VIEW csvw_all_jobs_masterv2
-- Active Jobs
SELECT TOP (100) PERCENT
    J.WS_Job_Number AS JobNumber,
    J.WS_Job_Name AS JobName,
    J.User_Define_1 AS JobDescription,
    J3.User_Define_1 AS JobNote,
    J.Divisions AS Division,
    J.Job_Address_Code AS AddressCode,
    J.Bill_Customer_Number AS CustomerCode,
    J.Estimator_ID AS SalesmanID,
    J.Expected_Contract AS ExpectedContract,
    J.Calc_Pct_Compl_to_Date AS PercentComplete,
    J.Est_Equipment_Cost AS EstEquipment,
    J.Est_Material_Cost AS EstMaterial,
    J.Est_Cost_UserDef1 AS EstSubs,
    J.Est_Labor_Cost AS EstLabor,
    J.Est_Misc_Other_Cost AS EstMisc,
    J.Est_Cost_UserDef2 AS EstBurden,
    J.Est_Cost_UserDef3 AS EstContingency,
    J.Total_Estimated_Cost AS TotalEstimate,
    J.Act_Equipment_Cost_TTD AS ActEquipment,
    J.Act_Materials_Cost_TTD AS ActMaterial,
    J.Act_Cost_TTD_UserDef1 AS ActSubs,
    J.Act_Labor_Cost_TTD AS ActLabor,
    J.Act_Cost_TTD_UserDef2 AS ActBurden,
    J.Act_Misc_Other_Cost_TTD AS ActMisc,
    J.Total_Actual_Cost AS TotalActual,
    J.Committed_Equipment_TTD AS CommEquipment,
    J.Committed_Materials_TTD AS CommMaterial,
    J.Committed_TTD_UserDef1 AS CommSubs,
    J.Committed_Labor_TTD AS CommLabor,
    J.Committed_Subs_TTD AS CommRental,
    J.Committed_Other_TTD AS CommOther,
    J.Committed_Cost AS TotalCommitted,
    J.Revsd_Equip_Forecasted AS ForecastEquip,
    J.Revsd_Materials_Forecst AS ForecastMaterial,
    J.Revsd_Forecast_UserDef1 AS ForecastSubs,
    J.Revsd_Labor_Forecasted AS ForecastLabor,
    J.Revsd_Other_Forecst_Cst AS ForecastOther,
    J.Revsd_Forecast_UserDef2 AS ForecastBurden,
    J.Revsd_Forecast_UserDef3 AS ForecastContingency,
    J.Tot_Revsd_Forecast_Cost AS TotalForecast,
    J.Est_Labor_Units_TTD AS EstHours,
    J.Act_Labor_Units_TTD AS ActHours,
    J.CREATDDT AS CreateDate,
    COALESCE(J3.Close_Date, CAST('1900-01-01' AS datetime)) AS CloseDate,
    CASE 
        WHEN J3.Close_Date IS NOT NULL THEN 'Closed'
        WHEN J.WS_Inactive = 1 THEN 'Inactive'
        ELSE 'Open'
    END AS Status,
    J.Net_Billed_TTD AS NetBilled,
    J.Cash_Received_TTD AS CashReceived,
    J.Last_Billing_Date AS LastBillingDate,
    J.Est_Cost_UserDef4 AS EstWarranty,
    J.Act_Cost_TTD_UserDef4 AS ActWarranty,
    J.Revsd_Forecast_UserDef4 AS ForecastWarranty,
    J7.User_Define_1 AS EstOTHours,
    J7.User_Define_2 AS EstManpower,
    J7.User_Define_3 AS MaterialCostAnalysis
FROM JC00102 AS J
LEFT JOIN JC30001 AS J3 ON J.WS_Job_Number = J3.WS_Job_Number
LEFT JOIN JC00107 AS J7 ON J.WS_Job_Number = J7.WS_Job_Number

UNION

-- Closed Jobs
SELECT TOP (100) PERCENT
    J3.WS_Job_Number AS JobNumber,
    J3.WS_Job_Name AS JobName,
    J3.User_Define_1 AS JobDescription,
    J3.User_Define_1 AS JobNote,
    J3.Divisions AS Division,
    J3.Job_Address_Code AS AddressCode,
    J3.Bill_Customer_Number AS CustomerCode,
    J3.Estimator_ID AS SalesmanID,
    J3.Expected_Contract AS ExpectedContract,
    J3.Calc_Pct_Compl_to_Date AS PercentComplete,
    J3.Est_Equipment_Cost AS EstEquipment,
    J3.Est_Material_Cost AS EstMaterial,
    J3.Est_Cost_UserDef1 AS EstSubs,
    J3.Est_Labor_Cost AS EstLabor,
    J3.Est_Misc_Other_Cost AS EstMisc,
    J3.Est_Cost_UserDef2 AS EstBurden,
    J3.Est_Cost_UserDef3 AS EstContingency,
    J3.Total_Estimated_Cost AS TotalEstimate,
    J3.Act_Equipment_Cost_TTD AS ActEquipment,
    J3.Act_Materials_Cost_TTD AS ActMaterial,
    J3.Act_Cost_TTD_UserDef1 AS ActSubs,
    J3.Act_Labor_Cost_TTD AS ActLabor,
    J3.Act_Cost_TTD_UserDef2 AS ActBurden,
    J3.Act_Misc_Other_Cost_TTD AS ActMisc,
    J3.Total_Actual_Cost AS TotalActual,
    J3.Committed_Equipment_TTD AS CommEquipment,
    J3.Committed_Materials_TTD AS CommMaterial,
    J3.Committed_TTD_UserDef1 AS CommSubs,
    J3.Committed_Labor_TTD AS CommLabor,
    J3.Committed_Subs_TTD AS CommRental,
    J3.Committed_Other_TTD AS CommOther,
    J3.Committed_Cost AS TotalCommitted,
    J3.Revsd_Equip_Forecasted AS ForecastEquip,
    J3.Revsd_Materials_Forecst AS ForecastMaterial,
    J3.Revsd_Forecast_UserDef1 AS ForecastSubs,
    J3.Revsd_Labor_Forecasted AS ForecastLabor,
    J3.Revsd_Other_Forecst_Cst AS ForecastOther,
    J3.Revsd_Forecast_UserDef2 AS ForecastBurden,
    J3.Revsd_Forecast_UserDef3 AS ForecastContingency,
    J3.Tot_Revsd_Forecast_Cost AS TotalForecast,
    J3.Est_Labor_Units_TTD AS EstHours,
    J3.Act_Labor_Units_TTD AS ActHours,
    J3.CREATDDT AS CreateDate,
    J3.Close_Date AS CloseDate,
    'Closed' AS Status,
    J3.Net_Billed_TTD AS NetBilled,
    J3.Cash_Received_TTD AS CashReceived,
    J3.Last_Billing_Date AS LastBillingDate,
    J3.Est_Cost_UserDef4 AS EstWarranty,
    J3.Act_Cost_TTD_UserDef4 AS ActWarranty,
    J3.Revsd_Forecast_UserDef4 AS ForecastWarranty,
    J37.User_Define_1 AS EstOTHours,
    J37.User_Define_2 AS EstManpower,
    J37.User_Define_3 AS MaterialCostAnalysis
FROM JC30001 AS J3
LEFT JOIN JC30107 AS J37 ON J3.WS_Job_Number = J37.WS_Job_Number;
